export const START_LOGIN = 'START_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_SECTION = 'CHANGE_SECTION';

export const START_POSTING = 'START_POSTING';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAIL = 'POST_FAIL';

export const CHANGE_POST = 'CHANGE_POST';
export const CHANGE_POST_SUCCESS = 'CHANGE_POST_SUCCESS';
export const CHANGE_POST_FAIL = 'CHANGE_POST_FAIL';

export const REMOVE_POST = 'REMOVE_POST';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST_FAIL = 'REMOVE_POST_FAIL';

export const ADD_IMAGE = 'ADD_IMAGE';
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_FAIL = 'ADD_IMAGE_FAIL';

export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const REMOVE_IMAGE_SUCCESS = 'REMOVE_IMAGE_SUCCESS';
export const REMOVE_IMAGE_FAIL = 'REMOVE_IMAGE_FAIL';